### ISSUE TITLE
Unable to login to V12 Install

### ISSUE THREAD

**Issue by luxosis** [erdomke/Innovator.Client#15]
I'm unable to work out how to login to a Innovator 12SP0 installation using the Innovator Client library. I'm testing it using the code below (just a basic console app for testing), it works perfectly on 11SP9 and 11SP12 installations, however with 12SP0 the last line throws an exception with the message "Unauthorised".

I've tried to work out how to handle V12, it looks like it should be handled automatically and I can't seem to find any clues as to what I should do differently.

Any help or ideas would be hugely appreciated!

```
     IRemoteConnection Connection = Factory.GetConnection(_connectionPreferences, true).Wait();
      databases = Connection.GetDatabases();
      ExplicitCredentials loginCredentials = new ExplicitCredentials(databases.First(), username, password);
      Connection.Login(loginCredentials, false).Wait();
```

**Comment by erdomke** [comment]
If you are on the latest version of the package, then the code you have should work correctly. (I am using the latest version against v12 currently.) However, authentication changed with Aras v12 and older versions of the Innovator.Client library will not work with a v12 Aras install.
