### ISSUE TITLE
Invalid Attribute retrieving server variable

### ISSUE THREAD

**Issue by VirtualWebSoftware** [erdomke/Innovator.Client#21]
Using the innovator.client.IOM object to retrieve a server variable, am getting this error:

System.Xml.XmlException: ''<', hexadecimal value 0x3C, is an invalid attribute character. Line 1, position 29.'

  AdminEmail =  IOMInnovator.getItemByKeyedName("Variable", "NAME").getProperty("value");

server running Version: 11.0 SP7; Build: 6423

**Comment by erdomke** [comment]
This is fixed in the latest NuGet package which is being released.
