### ISSUE TITLE
TimeZone test is broken

### ISSUE THREAD

**Issue by broderickhyman** [erdomke/Innovator.Client#25]
Test Name:	TimeZoneTests
Test Outcome:	Failed
Result StackTrace:	at Innovator.Client.Tests.PropertyTests.TimeZoneTests() in C:\Projects\GCAE\Innovator.Client\src\Innovator.ClientTests\Aml\PropertyTests.cs:line 69
Result Message:	Assert.AreEqual failed. Expected:<1/1/2020 8:00:00 AM>. Actual:<1/1/2020 9:00:00 AM>.

Values when this breaks:
winter: {1/1/2020 12:00:00 PM}
zone: {(UTC-04:00) Cuiaba}
custZone: {Innovator.Client.DateTimeZone} "Central Brazilian Standard Time" {(UTC-04:00) Cuiaba}

**Comment by erdomke** [comment]
I think this is fixed in the latest commits. If it ever fails again, you can open the `Innovator.Client.Net45.sln` and run `Innovator.Client.TzUtils.GenerateRecords(@"{PATH_TO_REPO}\src\Innovator.Client\Aml\TimeZoneInfo.Records.cs")` from the immediate window.
