### ISSUE TITLE
Auto set ApplyAML CommandAction when using conn.Apply()

### ISSUE THREAD

**Issue by broderickhyman** [erdomke/Innovator.Client#26]
In order to do a ApplyAML you have to wrap the aml string with new command() and then add the action. AML tags are already detected in Command.cs line 180, we should also do it in Command.WithAml().

**Comment by erdomke** [comment]
I think this is fixed in the latest commits. If it ever fails again, you can open the `Innovator.Client.Net45.sln` and run `Innovator.Client.TzUtils.GenerateRecords(@"{PATH_TO_REPO}\src\Innovator.Client\Aml\TimeZoneInfo.Records.cs")` from the immediate window.

**Comment by erdomke** [comment]
The reason I can do that with good performance on line 180, is I already have a parsed representation of the AML in memory at that moment. Therefore, I can precisely determine that you are trying to execute a query that has multiple top-level `<Item>` tags that will require `ApplyAML`. I don't want to do that any time I see an `<AML>` as you might have have wrapped a single `<Item>` query in `<AML>` tags. In that scenario, `ApplyAML` won't return any string results from methods which could cause weird bugs and issues in your code. (Blame Aras; I don't know why they have this odd behavior.)
