### ISSUE TITLE
.NET 5 Hash Error

### ISSUE THREAD

**Issue by caleb1994** [erdomke/Innovator.Client#35]
Microsoft has released that there is a breaking change with the System.Security.Cryptography.Algorithms with .NET 5. The issues occur if the ConnectionPreferences contain credentials when Factory.GetConnection is ran, as well as if the connection is established, and then Login() is executed using anything but the ExplicitHashCredentials method of creating credentials.

**Comment by broderickhyman** [comment]
It seems like this is limited to Blazor WebAssembly
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly
