### ISSUE TITLE
What type of licensing?

### ISSUE THREAD

**Issue by Thraganux** [erdomke/Innovator.Client#5]
Hello,
I am trying to find the licensing for Innovator.Client and InnovatorAdmin repositories.  Have you added licensing to this?  Or am I terrible at looking?

These are great tools which i'd like to use and add to, but I have to make sure the licensing is one which I could use in my environment.

**Comment by erdomke** [comment]
Sorry for the delay in response. It looks like InnovatorAdmin originally had the BSD license called out.  However, since the MIT license seems to be simpler (and equally permissive), I'm adding that to both repositories.  If that doesn't work for your use case, let me know.
