### ISSUE TITLE
Works great - question about adding content

### ISSUE THREAD

**Issue by bradmartin333** [erdomke/Innovator.Client#50]
I don't use Aras much, so this might not make sense.
I am creating tooling to help the Mechanical Engineers in my office.
They liked my [demo of using this repo for a dependency graph](https://github.com/bradmartin333/SandboxUI/blob/62ff4e9bc94eb868c02632b62fbc2dc0de4dc523/SandboxUI/ArasAPI/Program.cs) and asked if I could automate adding .pdf files to an Aras part.
Is that possible? There is a software admin in charge of Aras, I haven't asked him yet, but it seems like Aras has a lot of features that aren't enabled in our web environment.

**Comment by broderickhyman** [comment]
@bradmartin333 This project is a community project not associated with Aras and most functionality questions should be asked on their [forums](https://www.aras.com/community). That being said, I do know it is possible to automate uploading pdf files using this library.
