### ISSUE TITLE
Behavior not honored

### ISSUE THREAD

**Issue by Tolectin** [erdomke/Innovator.Client#51]
I'm trying to load a CAD Structure relationship, and I'm trying to force the behavior to be hard_fixed.  Currently I have the CAD Structure relationship type's behavior set to float within Aras.  When I apply my AML and look at the database, the source_id and the related_id look correct (as if the hard_fixed was honored), but the behavior value is set to float.  Is this expected?

**Comment by kentonvk** [comment]
I am not exactly sure what you are seeing and what the setup is, but this behavior is not controllable through any AML calls, or with Innovator.Client. You may have better luck with this question in the Innovator forums.

**Comment by broderickhyman** [comment]
Closing as not applicable.
