### ISSUE TITLE
Unable to connect to Innovator Server

### ISSUE THREAD

**Issue by MarvinNorway** [erdomke/Innovator.Client#7]
@erdomke 
Not sure if this is a bug or if I'm just doing it wrong.
I couldn't find anywhere to ask for help, so I'm just filing this as an issue out of desparation:

I want to connect to an Aras InnovatorServer 11.0 SP12.
To access it in the browser, I navigate to:

http://myserver/InnovatorStaging
which redirects to
http://myserver/InnovatorStaging/Client/X-salt=201810311354_11.0.0.6920-X/default.aspx

I then see my Windows username (not possible to change) and the database "InnovatorStaging".
I am not prompted for any password, so I assume it uses Windows authentication.

I'm trying to access the same server in code like this:

```
var conn = Factory.GetConnection("http://myserver/InnovatorStaging/", "MyApplication");
conn.Login(new WindowsCredentials("InnovatorStaging"));
```
That results in an AggregateException with the following InnerException:

```
Innovator.Client.HttpException: Unauthorized
   at Innovator.Client.SyncClientHandler.Send(HttpRequest request)
   at Innovator.Client.SyncHttpClient.Send(HttpRequest request)
   at Innovator.Client.HttpClientExtensions.SendSync(SyncHttpClient service, HttpRequest req, LogData trace)
```
I have also tried with ExplicitCredentials, but that didn't help either.

And I just tried with IOM.dll (version 10.0.0.5926 - might be an outdated version, I'm not sure):

```
var connection = IomFactory.CreateWinAuthHttpServerConnection("http://myserver/InnovatorStaging/", "InnovatorStaging");
var loginResult = connection.Login();
```

This works like a charm!

So what am I doing wrong or how can I debug this?

**Comment by broderickhyman** [comment]
Are you working in a vanilla instance?
I don't know the particulars with the WindowsCredentials, but I just verified ExplicitCredentials on a vanilla install.

> var conn = Factory.GetConnection("http://localhost/Innovator", "Console Test");
> conn.Login(new ExplicitCredentials("InnovatorSolutions", "admin", "innovator"));

**Comment by MarvinNorway** [comment]
It's not a vanilla instance, but we definitely didn't make any changes to authentification.
And also IOM works just fine - I thought this was just a wrapper around IOM?

**Comment by erdomke** [comment]
From what you are describing, it sounds like you are making all the correct calls. I will trying to do some more debugging with Windows credentials in a test instance. This library is not merely a wrapper around the IOM as there are many complaints I had with the IOM which I could not fix by simply wrapping it. As a result, there is probably some bug that has yet to be fixed which I will try and look for.

**Comment by MarvinNorway** [comment]
Thanks. Please let me know if I can help.

**Comment by MarvinNorway** [comment]
@erdomke Any news on this? I'd really like to start using your library because IOM.dll is killing me.
I'm going to get trouble with my neck because I just keep shaking my head looking at the code.

**Comment by erdomke** [comment]
I finally got around to creating a test instance and releasing a fix for this to NuGet. If you are still having issues, let me know.

**Comment by MarvinNorway** [comment]
Thanks! I'll give it a try. What was the issue?

**Comment by erdomke** [comment]
Apparently I did everything but actually send the credentials in that branch of the code. They're being sent now.

**Comment by MarvinNorway** [comment]
Great. How stable is this library? Would you use it for production purposes?

**Comment by erdomke** [comment]
I would say it stable and production-ready. At my old job (for a medium-sized automotive supplier), it was the only library used for communication between custom clients (both legacy desktop applications and newer web applications) and Innovator. These clients were used in production by approximately 1400 distinct users each week. It also was used in some server-side dlls and powers the InnovatorAdmin tool that is used in several organizations for Aras Innovator development work.

**Comment by MarvinNorway** [comment]
Thanks!

**Comment by Barkatkhan89** [comment]
Hi @erdomke ,

I am trying same thing but gets an error  : 
**"Credentials of type WindowsCredentials are not supported"**


StrackTrack : 
 "   at Innovator.Client.OAuthAuthenticator.HashCredentials(ICredentials credentials)\r\n   at Innovator.Client.OAuthAuthenticator..ctor(HttpClient service, OAuthConfig config, ICredentials creds)\r\n   at Innovator.Client.AuthenticationFactory.<>c__DisplayClass0_0.<GetAuthenticator>b__1(IHttpResponse r)\r\n   at Innovator.Client.Promise`1.Done(Action`1 callback)\r\n   at Innovator.Client.AuthenticationFactory.GetAuthenticator(Uri innovatorServerBaseUrl, HttpClient service, ICredentials creds, Boolean async)\r\n   at Innovator.Client.Connection.ArasHttpConnection.GetAuthenticator(ICredentials credentials, Boolean async)\r\n   at Innovator.Client.Connection.ArasHttpConnection.Login(ICredentials credentials, Boolean async)\r\n   at Innovator.Client.Connection.ArasHttpConnection.Login(ICredentials credentials)\r\n   at PerformanceTool.Program.Main(String[] args)


can please guide here,

aditionally i would be nice if you can provide an example to use it in a WebApi Project.

Thanks.
