### ISSUE TITLE
login exception

### ISSUE THREAD

**Issue by hyfbeetle** [erdomke/Innovator.Client#8]
download innovator.client yestoday. arashttpconnection login throws excepion, one or more problems happened. what is wrong? thanks very much.

**Comment by erdomke** [comment]
After some testing, I realized that authentication doesn't work currently with 11sp14 and 11sp15. I am in the process of releasing a fix for this, `v2019.3.9.1701`. If this does not fix the problem, please let me know the version of innovator and type of authentication you are using.

**Comment by hyfbeetle** [comment]
thanks you very much. 
I made a mistake,  using ExplicitCredentials, but md5 hash passwd. can it tell me which is wrong, assert info is ok, I will try it.
